name: AdvancedDiscord
version: '${project.version}'
main: me.gotitim.advanceddiscord.AdvancedDiscord
api-version: 1.19
authors: [ gotitim ]
description: An advanced plugin for connecting minecraft and discord
load: STARTUP
commands:
  dynlist:
    permission: advanceddiscord.dynlist
permissions:
  advanceddiscord.dynlist:
    default: op